### PR TITLE
#160174240 Add forms to update user and admin details

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Adds forms for Users and Admins to update account registration details

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/speedy_chakula/archive/ft-update-user-and-admin-160174240.zip) the repo
* Extract and navigate into the `speedy_chakula` folder
* in the `UI` folder, open `update_user_details.html` and `update_admin_details` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/speedy_chakula.git`

* Run `git checkout ft-update-user-and-admin-160174240`

* Run `cd speedy_chakula/UI/`

* Open user_order_history.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#160174240](https://www.pivotaltracker.com/story/show/160174240)

#### Screenshots 

screenshot from 2018-09-01 18-41-50
screenshot from 2018-09-01 18-58-25

#### Questions:

### CODE REVIEW

**Comment by Gabkings** [comment]
**iko poa si baya**

**Comment by Darius-Ndubi** [comment]
great work i see you working on more features, you  covering all possibilities of a user.

**Comment by artorious** [comment]
@Gabkings @Darius-Ndubi Thanks for your input. Highly appreciated. 
I've made changes to improve readability and color schemes. 
Check out my changes #8

**Comment by Kalela** [comment]
LGTM

**Pull request merged**
