### PR TITLE
#160173828 Add form to make food orders 

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Add websites' food order form for signed in users to make orders

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a web browser:

* [Download](https://github.com/artorious/speedy_chakula/archive/ft-make-food-orders-160173828.zip) the repo
* Extract and navigate into the `speedy_chakula` folder
* in the `UI` folder, open `food_order.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/speedy_chakula.git`

* Run `git checkout ft-make-food-orders-160173828`

* Run `cd speedy_chakula/UI/`

* Open food_order.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#160173828](https://www.pivotaltracker.com/story/show/160173828)

#### Screenshots 
screenshot from 2018-08-31 13-54-17

#### Questions:

### CODE REVIEW

**Comment by PromasterGuru** [comment]
Hey bro, very good design and alignment of items. However, Very bright colors are not recommended.

**Comment by PromasterGuru** [comment]
Hey bro. Try to use color codes. The following link might be helpful https://htmlcolorcodes.com/color-picker/

**Comment by EmmanuelBeja** [comment]
Colors.

**Comment by EmmanuelBeja** [comment]
Try play with a little less bright colors. Some colors don't go well together as well.

**Comment by artorious** [comment]
@PromasterGuru @EmmanuelBeja Thanks for your input. Highly appreciated. 
Made changes to improve readability and color schemes. 
Check out my changes #8

**Comment by Kalela** [comment]
LGTM

**Pull request merged**
